server:
  port: 8081 # Inventario correrá en el puerto 8081
  servlet:
    context-path: /inventario

spring:
  application:
    name: distrimarket-inventario
  devtools:
    restart:
      enabled: false

  # Configuración de la Base de Datos (PostgreSQL)
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:pos_db}?sslmode=require
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true # Útil tenerlo en true durante el desarrollo para ver las consultas en consola

  # Configuración de Liquibase (Hereda los changelogs de commons)
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

# Configuración de Spring Cloud OpenFeign
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    url: /openapi.yaml
    operations-sorter: method
    tags-sorter: alpha
  default-produces-media-type: application/json
  override-with-generic-response: false

info:
  app:
    version: '@project.version@'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    status-page-url-path: /inventario/actuator/info
    health-check-url-path: /inventario/actuator/health